version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth: 
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      
      - run: 
          name: "build and push the image"
          command: |
            TAG=latest
            docker build -t $DOCKERHUB_USER/kylekorv3-web-frontend:$TAG ./frontend
            docker build -t $DOCKERHUB_USER/kylekorv3-web-api:$TAG ./api
            docker build -t $DOCKERHUB_USER/kylekorv3-web-nginx:$TAG ./nginx
            docker build -t $DOCKERHUB_USER/kylekorv3-web-worker:$TAG ./worker
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
            docker push $DOCKERHUB_USER/kylekorv3-web-frontend:$TAG
            docker push $DOCKERHUB_USER/kylekorv3-web-api:$TAG 
            docker push $DOCKERHUB_USER/kylekorv3-web-nginx:$TAG 
            docker push $DOCKERHUB_USER/kylekorv3-web-worker:$TAG 

workflows:
  only_build:
    jobs:
      - build
